### ISSUE TITLE
Git on Computer/SMC

### ISSUE THREAD

**Issue by JoeJimFlood** [uwhpsc-2016/syllabus#27]
I already have Python and Git installed on my computer (I use Visual Studio to edit Python scripts). Will I need to pay the fee for SMC? I have already cloned the homework 1 repository onto my computer and edited the scripts, and it seems that there are no problems thus far.

**Comment by cswiercz** [comment]
My policy on the use of your own computer instead of SMC is the following:

I am _very strongly suggesting_ that students use SMC because (1) it already has all of the tools we need for the course, (2) there is the potential of running into issues when trying to install these tools yourself, and (3) it is a unified computing environment. Because of the number of students taking the course I have chosen SMC as a unified compute platform so that myself and the TAs do not have to spend time acting as systems administrators and, instead, can spend time helping students understand the central questions surrounding HPSC. (Installation issues are not central to HPSC.)

An additional note, which applies to your particular case, is that the compilation instructions and some syntax on Windows platforms is different from those of Unix / Linux platforms. _I have no experience with software development on Windows platforms_. If you have any any OS-dependent questions you will have to resolve them yourself.

This will become much more relevant when we start talking about C and compiled languages. (Tomorrow.) Sometimes, just because code compiles on Unix does not mean it compiles on Windows.

A very large majority of scientific software tools are developed and used on Unix/Linux-type platforms. That is not to say that Windows does not have a place in scientific computing. Making such software available for Windows often, at least in my experience, is considered an afterthought.

**Comment by JoeJimFlood** [comment]
Ok. Thanks for letting me know!
